### ISSUE TITLE
Register attribute output handlers via di.xml

### ISSUE THREAD

**Issue by thomas-kl1** [magento/devdocs#8587] opened 2021-01-29 09:35 UTC
# New feature request

## Description

Register new attribute output handlers via the di.

Issue: https://github.com/magento/magento2/issues/12371
Pull Request: https://github.com/magento/magento2/pull/24405

## Expected result

The developer can add new attribute output handlers via the dia without having to edit the templates/theme which reduce maintenance and cost and is great for extensibility.

## Benefits

This feature allows to add output handler without modifying the templates/themes for specific attribtues

## Possible solutions

Developer guide:

```xml
<type name="Magento\Catalog\Helper\Output">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="productattribute" xsi:type="array">
                <item name="myHandler" xsi:type="object">Vendor\Module\Model\Handler\Output</item>
            </item>
            <item name="categoryattribute" xsi:type="array">
                <item name="myHandler" xsi:type="object">Vendor\Module\Model\Handler\Output</item>
            </item>
        </argument>
    </arguments>
</type>
```

Where `Vendor\Module\Model\Handler\Output` is:

```php
namespace  Vendor\Module\Model\Handler;

use Magento\Catalog\Helper\Output as HelperOutput;

class Output
{
    public function productAttribute(HelperOutput $output, string $attributeHtml, array $params): string
    {
        // $params: ['product' => $product, 'attribute' => $attributeName]
        // todo your output handler
        return $attributeHtml;
    }

    public function categoryAttribute(HelperOutput $output, string $attributeHtml, array $params): string
    {
        // $params: ['category' => $category, 'attribute' => $attributeName]
        // todo your output handler
        return $attributeHtml;
    }
}
```

**Comment by dineshvb** [comment] 2021-01-29 15:29
@magento I am working on this

**Comment by nahall** [comment] 2021-01-29 22:22
Can you confirm if this code does work for you? I'm trying it out but the productAttribute function in Vendor\Module\Model\Handler\Output never gets run. I can see the constructor in Vendor\Module\Model\Handler\Output firing, though, but when I trace through Magento\Catalog\Helper\Output I can't see this new handler being added anywhere. Thanks.

**Comment by thomas-kl1** [comment] 2021-01-29 22:30
@nahall sorry there was a typo in the xml, please try again, but set the key in lowercase in the di (I have updated the description)

**Comment by nahall** [comment] 2021-01-29 22:51
Ah, I had found the first typo but didn't realize that productattribute was case sensitive. It seems to be working now. Thanks much!

**Comment by danidelcar** [comment] 2021-08-04 14:44
Hi @thomas-kl1 do you think we could close this issue?, was it just a typo then?. Thanks!

**Comment by thomas-kl1** [comment] 2021-08-04 19:01
Hi @danidelcar it doesn't seems that the feature has been documented in the Magento Devdoc, so the issue should remain open.

**Comment by dshevtsov** [comment] 2024-09-03 21:15
The Magento developer documentation was migrated to [Adobe Commerce Developer Documentation](https://developer.adobe.com/commerce/docs/).
If the issue is still relevant, please feel free to reopen the issue in the [corresponding project](https://github.com/topics/adobe-commerce-devsite).

**Closed by dshevtsov** 2024-09-03 21:15 UTC
Labels: Progress: ready for dev
