### ISSUE TITLE
Clarify compatible Elasticsearch versions

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#5488] opened 2019-09-26 07:08 UTC
# General issue

## Description:

It's not really clear what exact Elasticsearch versions supported.
On some pages we have "Elasticsearch 6.x", on some "Elasticsearch 6.0+" (that probably means 7.x is supported).

Please update in all places to reflect that ES 7.x is not supported (or is it supported?).
Examples:
- Elasticsearch 5.0+/6.0+
https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#configure-elasticsearch-within-magento
- Elasticsearch 6.0+ https://docs.magento.com/m2/ce/user_guide/catalog/search-elasticsearch.html?itm_source=merchdocs_ce&itm_medium=quick_search&itm_campaign=federated_search&itm_term=elastc#step-1-configure-search-options
- Elasticsearch 6.x https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#elastic-m2-configure

**Comment by ihor-sviziev** [comment] 2019-09-30 06:37
Following issues not clear understanding. Example https://github.com/magento/magento2/issues/24777

**Comment by extremeskillz** [comment] 2019-09-30 14:06
Please note Ubuntu repo keep the current versions of elasticsearch there. Anyone running mangento on debian based system will get the latest and greatest by update. This will break Magento2.3.2 if you rely on ubuntu repos for updates. Support needs to be added to Magento2 with composer update.

**Comment by shrielenee** [comment] 2019-10-03 18:39
Possible steps for resolving this:
1. Confirm correct version to publicize.
2. Possibly add a warning label?
3. Clarify field options in the UI.

**Comment by dobooth** [comment] 2020-01-14 20:03
Part of the issue is that the UI has versions hard coded in. The UI might say 7+ but that includes versions of 7 we might yet support.

**Comment by dobooth** [comment] 2020-01-15 19:31
https://github.com/magento/community-features/issues/231

**Comment by dobooth** [comment] 2020-02-12 19:28
Fix is in for the UI change that will clarify this.

**Comment by dobooth** [comment] 2020-04-01 16:02
I have updated supported ES version numbers in 2.3.5 and 2.4. More work will need to be done around MySQL. Closing for as Fixed.

**Closed by dobooth** 2020-04-01 16:02 UTC
Labels: Groomed, Help Wanted, Progress: dev in progress
