### ISSUE TITLE
Subscription and 404 message

### ISSUE THREAD

**Issue by ychadwick** [magento/devdocs#1655] opened 2018-01-16 11:35 UTC
Feedback on page: /guides/v2.2/advanced-reporting/overview.html

There should be some information as to how to activate a subscription or to why users are finding a 404 page even though the module is activated
![screen shot 2018-01-16 at 12 34 40](https://user-images.githubusercontent.com/664349/34986911-a6f217ca-fab9-11e7-9dd4-527aed116dd6.png)
![screen shot 2018-01-16 at 12 34 22](https://user-images.githubusercontent.com/664349/34986916-ac396d78-fab9-11e7-9fa2-c006d39619b8.png)

**Comment by dshevtsov** [comment] 2018-01-16 13:05
@ychadwick thank you for your feedback!

Please see [Advanced Reporting](http://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html) in the Magento User documentation.
Let me know if it contains information you need, or not.

**Comment by ychadwick** [comment] 2018-01-16 13:07
Unfortunately it does not. There is no mention of 404 message. I have followed the exact steps as mentioned in this page, Our website matches all the requirements, the cronjob is setup and the Module is enabled.

I am apparently not the only person to come across this error.

**Comment by bengarvey** [comment] 2018-01-16 13:29
@ychadwick what is the url for your store?

**Comment by ychadwick** [comment] 2018-01-16 13:30
https://www.luxury-shops.com/ <https://www.luxury-shops.com/>

**Comment by owengalenjones** [comment] 2018-01-16 15:02
Hi @ychadwick I looked into your report, it's failing because we operated under the assumption that a Magento account would only have 1 `base_currency_code`.  We found out later that through plugins or other settings an account can have a `base_currency_code` per store.  We're actively working on supporting this situation and it should be resolved this week.

As per more visibility of errors within Advanced Reporting I'm aware of the problem and in agreement there needs to be more visibility.  I'm going to try to work out a viable solution to display better / usable error messages soon.

Thank you!

**Comment by bengarvey** [comment] 2018-01-16 15:43
@ychadwick We're currently having an issue processing data for stores that use multiple currencies. This should be resolved soon.

**Comment by ychadwick** [comment] 2018-01-16 15:44
Ok, thanks for your help. Even though our store is just in one currency, during the testing phase, the currency was set to USD then changed to CHF so there were about 5 orders during that migration phase from 1.9 to 2.1 that were accidentally made in the incorrect currency.

I have manually corrected those 18 orders so hopefully there will be clean, single currency data for the one Magento store.

Thank you for shedding some light on the problem.

Will the Advanced reporting become available, or do I need to obtain a new token?

**Comment by owengalenjones** [comment] 2018-01-16 15:50
Hi @ychadwick that matches what I'm seeing:

```
Data set has more than one currency. This is not a
situation we expected to happen. As a result the code is
not set up to handle it. {:currencies (["CHF"] ["USD"])}
```

the current token will be valid for retrieving the data once the Swiss Franc orders are removed.  However the data to be retrieved will not be "refreshed" until the cron process in your store runs the Advanced Reporting process again.

**Comment by ychadwick** [comment] 2018-01-16 15:53
Thank you.

P.S. the USD orders are being removed, Swiss Franc orders are the ones we want ;)

**Comment by owengalenjones** [comment] 2018-01-17 20:45
@ychadwick I have rolled out support for multiple currencies and confirmed I can run your store successfully.

**Comment by riprod** [comment] 2018-01-17 22:50
This does not appear to be the problem with my store. I use only one base currency. I am on SSL and a publically available domain. I have tried disabling Advanced Reporting, clearing all cache, even re-compiling and deploying static content again. Then re-enabling it. I still get the 404 page. see www.engelcoolers.com

**Comment by owengalenjones** [comment] 2018-01-18 18:11
Hello @riprod I have looked at your subscription and we are getting an unauthorized response when attempting to download the required file from your Magento store.  Basically during the signup process the Magento store gives us a token that should allow us to access that page.  I have no idea why the token provided by your store would be giving us unauthorized responses.  Are there any security settings within your store that might be interfering?

Thanks!

**Comment by owengalenjones** [comment] 2018-01-18 20:47
Ok I spoke with Magento core developers regarding this issue and this is what they said:

Based on the error message:

```
{"message":"Consumer is not authorized to access %resources","parameters":{"resources":"Magento_Analytics::analytics_api"}}
```

they believe it to be a user permissions issue within the store.

  1. in Admin panel System->Integrations
  2. ensure that a Magento Analytics user exists
  3. Open the user, in their API tab make sure it has Analytics->API resource checked

**Comment by dshevtsov** [comment] 2018-01-22 13:40
@ychadwick I have [committed](https://github.com/magento/devdocs/commit/df2e3c7e0af4bc1e026a04f626c9f6669e1f801f) an update to the topic with more details in Prerequisites and a link to User Guide.

**Comment by riprod** [comment] 2018-01-26 15:04
The Integrations permissions are not the issue. I already tried that and it doesn't help. One the magento support forum also says there is a problem with the multi currencies but I only use one currency.

**Comment by riprod** [comment] 2018-01-26 15:08
@dshevtsov - I have read your new prerequisites. On your number 3.

3. Successful subscription to the Advanced reporting.

There is no mention of how or where to do this. You can sign up for a 7 day trial for their full version but that is in conflict with the user docs and support team that say this is 100% free and no subscription required.

**Comment by bengarvey** [comment] 2018-01-26 15:38
@riprod what is your store url?

**Comment by riprod** [comment] 2018-01-26 15:51
www.engelcoolers.com

**Comment by riprod** [comment] 2018-01-26 16:11
In Integrations, what should the "Callback URL" and "Identity link URL" be ?

**Comment by ccondra** [comment] 2018-01-26 17:07
I received similar comments through the feedback form in the user guide, and updated the requirements for Advanced Reporting, and added a Troubleshooting section with instructions to verify the API permissions.   Another clarification made is that your account becomes active with the next scheduled cron update, rather than "within a few hours."  So before that, you'll still get the 404 page.

**Comment by bengarvey** [comment] 2018-01-26 18:31
@riprod For engelcoolers specifically we're getting an Unauthorized error for the Magento_Analytics permissions.

**Comment by riprod** [comment] 2018-01-26 19:04
@bengarvey So how would I troubleshoot or resolve that ?

**Comment by riprod** [comment] 2018-01-26 19:27
@bengarvey Is there a way to reproduce this?

**Comment by bengarvey** [comment] 2018-02-03 02:23
@riprod Working on an answer for you

**Comment by bengarvey** [comment] 2018-02-05 14:47
@riprod Can you email me directly on this? bgarvey@magento.com

**Comment by bengarvey** [comment] 2018-02-06 22:21
Getting closer to the bottom of this.

**Comment by ccondra** [comment] 2018-02-20 17:08
I reported this problem and the 404 page quite some time ago, and recently updated the requirements and added a troubleshooting section at the bottom of the topic. I don't know what more I can do at this point.

**Comment by dshevtsov** [comment] 2018-02-21 09:15
Seems that this issue has become an engineering issue, not the documentation one.
I am closing it.

**Comment by lucalorenzato** [comment] 2018-03-01 10:33
Hi, I've follow all the thread and all the fix, but it still doesn't work. I've only one base currency enabled and integration api setted correctly.
Is there any chance to make it work?

**Comment by bengarvey** [comment] 2018-03-01 15:25
@lucalorenzato hey, what is your store url? I'll see what we can do.

**Comment by lucalorenzato** [comment] 2018-03-01 15:39
Hi @bengarvey my website is https://www.mysexydesire.com still on development.
Thank you!

**Comment by ccondra** [comment] 2018-03-01 22:32
Just a note to explain that in keeping with our community standards, the link to the site has been removed.

**Closed** 2018-03-01 22:33 UTC
Labels: 2.2.x
