### ISSUE TITLE
The bin/magento cli reference contains way too many duplicated flags

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#9081] opened 2021-08-10 20:15 UTC
# Bug report

## Description

Hi guys, take a look at this page here: https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html
Search for any of these flags:
- `--help`
- `--quiet`
- `--version`
- `--ansi`
- `--no-ansi`
- `--no-interaction`
- `--verbose`

All these flags appear 112 times on the page, because they don't belong to a specific command, but to the `bin/magento` command itself.

In my opinion it makes no sense to list these same flags 112 times, as it makes the document harder to read if looking for something.

### Steps to reproduce

See above

## Expected result

See below

## Possible solutions

Potential solution could be to list these common flags one time at the top of the page, saying that you can use those flags for all other commands as well.
That way we only see the flags that are truly interesting for a specific command.

@dshevtsov

**Comment by BarnyShergold** [comment] 2021-08-11 15:33
@magento I am working on this

**Comment by dobooth** [comment] 2021-08-11 16:05
@dshevtsov

**Comment by BarnyShergold** [comment] 2021-09-06 13:19
@dshevtsov - Can we close this issue then or do you want to keep it open for reference? Means we don't have to  keep addressing it 😄

**Comment by hostep** [comment] 2021-09-06 19:53
As long as the issue isn't solved, it shouldn't be closed, right? (What's with the desperation to close issues? Open issues form the backlog of what still needs to happen, it makes little sense to close the ones that aren't addressed yet...)

**Comment by BarnyShergold** [comment] 2021-09-07 08:41
> As long as the issue isn't solved, it shouldn't be closed, right? (What's with the desperation to close issues? Open issues form the backlog of what still needs to happen, it makes little sense to close the ones that aren't addressed yet...)

No desperation - just trying to clear up issues that don't need to be open so we don't end up looking at the same ones over and over. Question - is it possible to have a new label? Eg "Backlog" then issues like this can be flagged, left open and perhaps even discussed during maintainer calls?

**Comment by dshevtsov** [comment] 2021-09-07 19:34
I agree with @hostep. @BarnyShergold, I added the _Help Wanted_ label, because, technically, I'm not the only one who can do it.

**Comment by hostep** [comment] 2021-09-07 19:42
@dshevtsov: maybe it can help if you can link to the script that is used to generate that page.
Then if somebody is interested in figuring out how to fix this, he/she already knows what script needs to be tweaked and can give it a try.

**Comment by dshevtsov** [comment] 2021-09-07 20:22
Sure.

The topic assigns variables required by the script, and includes a file with the script: https://github.com/magento/devdocs/blob/master/src/guides/v2.4/reference/cli/magento.md

The file with script: https://github.com/magento/devdocs/blob/master/src/_includes/reference/cli-template.md

**Comment by dshevtsov** [comment] 2024-09-03 22:26
The reference was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/tools/cli-reference/commerce-on-premises).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.

**Closed by dshevtsov** 2024-09-03 22:26 UTC
Labels: Help Wanted, Progress: ready for dev

**Comment by hostep** [comment] 2024-09-04 18:46
Issue is still relevant, yet I'm too lazy to copy it to another repository.

Here's what I think could work:
- have a hardcoded list of global arguments/options to not output
- while rendering the arguments/options of a command, if it matches one of the list, skip outputting it
- at the top or bottom of the page, output the list of those global arguments/options and maybe link to it from each command

Shouldn't be very hard, but I don't have time for it and I'm not being paid for it

**Comment by dshevtsov** [comment] 2024-09-06 18:04
@hostep thank you for the feedback. I've been considering this format too, so I hope I get there through my backlog one day.
