### ISSUE TITLE
DevDocs in PDF version?

### ISSUE THREAD

**Issue by PrakashThapa** [magento/devdocs#483] opened 2016-01-18 21:41 UTC
I am not fan of online reading. Is it possible to generate Devdocs v2.0 in PDF format?

**Comment by xcomSteveJohnson** [comment] 2016-01-21 20:39
Sorry, no solution at this time. If you can suggest something, please let us know.

**Comment by DmitryRublev** [comment] 2016-03-02 15:31
I believe it's possible to implement plugin for Jekyll to generate PDF, or generate PDF from HTML with wkhtmltopdf or similar software. But it will take time and might (and probably will) require some tune-up.

Links to check: 
- [Peter J. Lu - Converting the website to documents](http://peterlu.github.io/2014/08/03/markdown_latex_pdf.html)
- [WeasyPrint](http://weasyprint.org/)

**Comment by jcalcaben** [comment] 2017-05-11 15:15
Closing Issue.
This is a duplicate of: https://github.com/magento/devdocs/issues/330

**Closed by jcalcaben** 2017-05-11 15:15 UTC
Labels: Enhancement
