### ISSUE TITLE
Feedback on page: /guides/v2.3/migration/migration-tool.html

### ISSUE THREAD

**Issue by brianpittvps** [magento/devdocs#7503] opened 2020-07-09 16:54 UTC
# General issue
Terminology is not explained
## Description:
The instructions for the data migration tool refer to "documents", but never tell you what a document is in the context of the data migration tool. To me, a "document" is a file with text in it that someone reads.  But you use it like a table in a database.  There are "document_rules" for ignoring or renaming "documents".  The "field_rules" refer to "some_document_1.field1", implying that documents are actually tables, but this is never explained.  What is a document?
## Possible solutions:
You have a "Terminology" section on the "How migration works" overview page, just add some more information there to explain what "document", "field", etc are.
## Additional information:

**Comment by keharper** [comment] 2020-07-09 18:44
Closing because it appears to be a duplicate of #7504

**Closed by keharper** 2020-07-09 18:44 UTC
