### ISSUE TITLE
Feedback on page: cloud/configure/setup-cron-jobs.html | link to support articule no allow access

### ISSUE THREAD

**Issue by amarroni** [magento/devdocs#7077] opened 2020-04-22 14:42 UTC
# Bug report

## Description
Reset stuck cron jobs manually on the cloud link re-direct you to a support ticket article but It's like special access needed to see the content.

### Steps to reproduce

1. go to <https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html>
1. On bottom of the page offer 2 links to continue reviewing corns
1. click on 'Reset stuck cron jobs manually on the cloud' 
1. you will redirect to <https://support.magento.com/hc/en-us/articles/360000097713-Reset-stuck-Magento-cron-jobs-manually-on-Cloud?_ga=2.30097595.548927178.1587387171-1949157112.1559396282>

## Expected result
See the article content talking about Rest stuck cron jogs manually on cloud

## Possible solutions
Changing the permission of the support article in order to be public access.

## Additional information
attached image showing no authorize access to see the article content

![image](https://user-images.githubusercontent.com/5198527/79995742-f8f0b080-848d-11ea-9257-192fd1eca301.png)

**Comment by dshevtsov** [comment] 2020-04-23 18:23
@almarchenko can you help with this?

**Comment by almarchenko** [comment] 2020-04-23 18:28
@dshevtsov  this article is unpublished, that is why it cannot be accessed. We are now trying to understand if it was intended or mistake.

**Comment by almarchenko** [comment] 2020-04-23 19:20
Was unpublished by mistake, fixed now.

**Comment by almarchenko** [comment] 2020-04-23 19:24
@amarroni  thank you for reporting this.

**Comment by meker12** [comment] 2020-04-23 19:26
Thanks for the quick fix @almarchenko!

**Comment by amarroni** [comment] 2020-04-23 20:04
> @amarroni thank you for reporting this.

It was a pleasure!

**Closed** 2020-04-23 20:04 UTC
Labels: Groomed, Progress: dev in progress
