### ISSUE TITLE
area types names are misleading - the description is not sufficient

### ISSUE THREAD

**Issue by steros** [magento/devdocs#1155] opened 2017-05-12 09:55 UTC
Feedback on page: /guides/v2.1/architecture/archi_perspectives/components/modules/mod_and_areas.html

It might be that for a native speaker this is more clear but for me this is very misleading.
I tried to overwrite the product model with
`<type name="Magento\Catalog\Model\Product" shared="false">`
but I placed the di.xml into the frontend subfolder as I wanted to affect the frontend.
After reading this documentation several times I figure that frontend only refers to all that handles display issues but has nothing to do with the product (display).

If this is correct the documentation should be much more clear and simple. Cause I think many will think that frontend affects all aspects of the frontend store and adminhtml is for the backend.

**Comment by almarchenko** [comment] 2017-05-17 12:49
Hi @steros 

>Cause I think many will think that frontend affects all aspects of the frontend store and adminhtml is > >for the backend.
And this is correct, `frontend ` are affects all aspects of the storefront, and adminhtml is for backend.

I'm not sure why your customization did not work as expected. I think you can post the question I on [Magento 2 GitHub](https://github.com/magento/magento2/issues), [Magento forum](https://community.magento.com/), or [stackexchange](http://magento.stackexchange.com/).

**Comment by steros** [comment] 2017-05-18 07:23
Hi @almarchenko,
thanks for your reply. But sorry to say this isn't the case.
We debugged this for quite some time. As long as the di.xml is in the frontend subfolder it isn't possible to extend Product in the frontend store.
Magento will not place the module into the array of modules to go over. This happens in var/generation/Magento/Catalog/Model/Product/Interceptor.php->load()
"$pluginInfo = $this->pluginList->getNext($this->subjectType, 'load');" this returns null always, whilst in the product detail page it doesn't. There (even with the di.xml in the frontend subfolder) getNext returns our plugin.
We didn't debug deeply enough to say why it does so but moving it from "frontend" to the root "etc" folder definitely solved the issue.
So either it doesn't work at all like this or it is a problem with overwriting the product model in specific.

Otherwise it might just be that the documentation is not correct and you have to specifically place it into the root or base folder. That's my guess at least.

**Comment by jeff-matthews** [comment] 2018-05-01 18:54
@buskamuza, will you please have an architect review whether our documentation is correct in this case?

**Comment by buskamuza** [comment] 2018-08-06 23:04
@steros, technically there should not be a restriction to load `di.xml` from a specific area. So I'd rather suggest you to file an issue at https://github.com/magento/magento2 with more specific use case and steps to reproduce.

But I'd also suggest you to look at our Tech Guidelines - https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#3-dependency-injection (3.3 and 3.4).
I'm not sure what's your use case, but it's a bad practice to apply anything presentation-related to a model. Model should behave the same independently of an area (whether it's regular storefront, Web API or CLI command). Area-specific configuration should impact presentation for specific area only.

**Comment by jeff-matthews** [comment] 2018-08-07 12:41
Thanks @buskamuza. 

@steros, I'm going to close this for now because it seems you may have found an issue with the code. We can reopen this if necessary after you report this to magento/magento2 and we can gather more information.

**Closed by jeff-matthews** 2018-08-07 12:41 UTC
Labels: Technical
