### ISSUE TITLE
Incorrect path for applying a theme

### ISSUE THREAD

**Issue by Matt-Price** [magento/devdocs#1211] opened 2017-06-11 16:21 UTC
This page:
devdocs/guides/v2.0/frontend-dev-guide/themes/theme-apply.md

states that to apply a theme you should go to:
In Admin, go to Stores > Configuration > Design.

This has changed and should now read:
In Admin, go to Content > Design > Configuration.

**Comment by hostep** [comment] 2017-06-11 16:52
It is still Stores > Configuration > Design for Magento 2.0.x.
Only in 2.1.x it was changed, and if you look at the [docs for version 2.1](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html), it is correct ;)

This has been reported a couple times before, it would be great if people first search for similar issues before they create a new issue :)

**Comment by keharper** [comment] 2017-06-12 14:13
This confusion was probably caused by a search returning a 2.0 article. We're looking at ways to reduce this type of error. 

I'm going to close this issue, because each version is correct.

**Closed by keharper** 2017-06-12 14:13 UTC
