### ISSUE TITLE
Consider consolidating backcompat docs

### ISSUE THREAD

**Issue by DrewML** [magento/devdocs#5473] opened 2019-09-24 23:06 UTC
# Topic clarification/correction request

## Topic Link

https://github.com/magento/devdocs/blob/master/src/guides/v2.4/contributor-guide/backward-compatible-development/index.md

https://github.com/magento/devdocs/blob/master/src/guides/v2.4/extension-dev-guide/versioning/codebase-changes.md

## Description

As far as I can tell, these documents overlap quite a bit, and it's not quite clear what the source of truth is.

## Possible solutions

Create a single document that is the source of truth for all backwards-compatible and backwards-incompatible change types.

**Comment by DrewML** [comment] 2019-09-24 23:10
cc @jcalcaben (don't have perms to assign you)

**Comment by shrielenee** [comment] 2020-09-03 19:04
Clearing the assignee because there has been no action on this since September 2019.

**Comment by BarnyShergold** [comment] 2020-09-21 10:40
@shrielenee - I've taken a look at these two pages and whilst they have similarities I don't feel they are close enough to even attempt to merge them into a single document. Plus they are approaching them from different points of view. One document is for contributors to make code changes to the Magento core itself and the other is for extension developers to take into consideration. In my opinion the documentation needs to stay separate. If you concur, can we close this issue?

**Comment by shrielenee** [comment] 2020-09-21 13:14
This issue cannot be closed @BarnyShergold. It was created by a Magento employee, is still relevant, and while the suggested approach may not be the right one, there is a way we can resolve the raised issue.

If you are not working the actual issue, you must remove yourself as the assignee so someone else can pick it up. I'll remove you for now. Thanks!

**Comment by BarnyShergold** [comment] 2020-09-21 13:22
That's odd I don't remember assigning myself this!

**Comment by dshevtsov** [comment] 2024-09-03 19:50
The topics were moved to:
* https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/
* https://developer.adobe.com/commerce/php/development/versioning/code-changes/

If the issue is still relevant, please reopen it in the corresponding repositories:
* https://github.com/AdobeDocs/commerce-contributor/issues
* https://github.com/AdobeDocs/commerce-php/issues

**Closed by dshevtsov** 2024-09-03 19:50 UTC
Labels: Help Wanted, Progress: ready for dev
