### ISSUE TITLE
Unable to View the Rest API documentation for Magento version 2.1.12

### ISSUE THREAD

**Issue by rehman0845** [magento/devdocs#7407] opened 2020-06-15 16:06 UTC
@magento Unable to View the Rest API documentation for Magento version 2.1.12
https://devdocs.magento.com/swagger/index_21.html
Can anybody provide the resource to view the REST API the documentation for Magento version 2.1.12? 
Thanks.

**Comment by manishmittalm** [comment] 2020-06-16 14:51
@rehman0845 
I think this has been deleted as Magento not providing support for Magento 2.1.

rest documents you can find here:
https://devdocs.magento.com/swagger/index_22.html
https://devdocs.magento.com/swagger/index_23.html

**Comment by manishmittalm** [comment] 2020-06-16 14:53
It is not a bug, Closing this issue, if you still need any hlep. Feel free to open it. Thanks

**Closed by manishmittalm** 2020-06-16 14:53 UTC
Labels: Progress: dev in progress
