### ISSUE TITLE
Feedback on page: /guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html

### ISSUE THREAD

**Issue by mohammadttc** [magento/devdocs#3554] opened 2019-01-11 01:39 UTC
# General issue
Broken link.
## Description:

There is a broken link at the following page.
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html
"UI components configuration" link is pointing to a 404 page.

**Comment by jeff-matthews** [comment] 2019-01-11 14:31
Thanks for reporting @mohammadttc. The issue is a double slash in the URL.

**Comment by dobooth** [comment] 2019-01-14 16:59
Fixed with https://github.com/magento/devdocs/pull/3567

**Closed by dobooth** 2019-01-14 16:59 UTC
Labels: 2.x, good first issue, groomed
