### ISSUE TITLE
Page does not exist on Magento Approved Best Practices 

### ISSUE THREAD

**Issue by brentwpeterson** [magento/devdocs#3134] opened 2018-10-19 13:34 UTC
# Bug report

https://devdocs.magento.com/community/resources/best-practices.html

Under -Magento approved best practices

Theme development best practices link is broken

Navigate to https://devdocs.magento.com/community/resources/best-practices.html
Click on https://devdocs.magento.com/frontend-dev-guide/theme-best-practice.html
You get a broken page

## Expected result

Page should exist

## Possible solutions

Link to correct page or create page

**Comment by jeff-matthews** [comment] 2018-10-19 13:51
Thanks for reporting this @brentwpeterson. Most of the links on that page are broken, unfortunately. I think I know what the problem is. We're using a variable (`{{page.baseurl}}`) for internal links, which works for relative links inside the `guides/` directory. Since the directory where this topic resides is outside of the `guides/` directory, we can't use the relative link variable the same way.  

We'll get this fixed right away.

**Comment by lorikrell** [comment] 2018-10-19 14:18
Getting this fixed ASAP!

**Comment by lorikrell** [comment] 2018-10-19 14:34
@brentwpeterson  -  Resolved with https://github.com/magento/devdocs/pull/3135!   The links will be updated in the source repo. Generated output will take a bit to update.

Thank you!

**Closed by lorikrell** 2018-10-19 14:34 UTC
Labels: Editorial
