### ISSUE TITLE
Verify if bug or needs update on "special price" text in configure-best-practices.html

### ISSUE THREAD

**Issue by gq-guo** [magento/devdocs#8906] opened 2021-04-30 08:01 UTC
# General issue

## Description:

special price did not lose effect at the scheduled date

magento open source 2.3

## Additional information:

special prices rules:
![image](https://user-images.githubusercontent.com/54096325/116666041-11fb3e00-a9cd-11eb-9298-3d0f06ad9f0f.png)

set special price, end date:2021-04-30
![image](https://user-images.githubusercontent.com/54096325/116665928-f2fcac00-a9cc-11eb-9eb5-fb05c68a2c61.png)

products on page:(2021-04-30) 
![image](https://user-images.githubusercontent.com/54096325/116666231-4d960800-a9cd-11eb-8232-e5773c1e291d.png)

**Comment by DenisSaltanahmedov** [comment] 2021-06-08 10:37
@magento I am working on this

**Comment by DenisSaltanahmedov** [comment] 2021-06-10 07:44
Hi, @shrielenee @dobooth I can not reproduce the issue. It seems the author of the issue had some problem with reindexing. I think we can close the issue.

**Comment by gamarshall** [comment] 2022-04-07 18:26
@gq-guo please confirm if this is still an issue.

**Comment by danidelcar** [comment] 2022-05-12 13:56
Hi @gq-guo you are welcome to reopen this issue again if you need, or have more information. Closing it due to no response

**Closed by danidelcar** 2022-05-12 13:56 UTC
Labels: Waiting for Response, Progress: dev in progress
