### ISSUE TITLE
"Get customer authorization token" page does have a content

### ISSUE THREAD

**Issue by atwixfirster** [magento/devdocs#7844] opened 2020-09-09 10:18 UTC
# Bug report

## Description

[Get customer authorization token](https://devdocs.magento.com/guides/v2.3/graphql/get-customer-authorization-token.html) page does have a content.

@keharper , could you please confirm the issue?

Because I see you removed all content from this page in https://github.com/magento/devdocs/commit/4524736df367b26579af02f9c5161b4ea309ab4a#diff-0b6fb511fd9b8b007e7802627358b4adL2.

Thank you!

### Steps to reproduce

1. Open
- https://devdocs.magento.com/guides/v2.3/graphql/get-customer-authorization-token.html
- https://devdocs.magento.com/guides/v2.4/graphql/get-customer-authorization-token.html

2. Page exists but contains an empty content.

## Expected result

The expected page content is: https://raw.githubusercontent.com/magento/devdocs/502840ce4e1c8a6b2121aef5f2ee9c9da3438239/guides/v2.3/graphql/get-customer-authorization-token.md

**Comment by BarnyShergold** [comment] 2020-09-10 15:44
This problem is due to redirects not being added correctly. I have checked and PR (#7843) will fix this as the file indicated will be removed and a redirect added to the new file

**Comment by atwixfirster** [comment] 2020-09-10 15:51
> This problem is due to redirects not being added correctly.

I am not sure about redirects. File exists but contains and empty content.

**Comment by BarnyShergold** [comment] 2020-09-10 16:28
What seems to happen sometimes is if a page is moving to a new location, someone creates the new file, moves the content, adds the redirect and then leaves the old file empty. This time it looks like they forgot to add the redirect.

What will happen when my PR is merged is that if you try and go to get-customer-authorization-token.html you get redirected to authorization-tokens.html (the new page has updated content)

**Comment by keharper** [comment] 2020-09-10 16:55
I'm pretty sure I used the `mv` or `git mv` command to rename the file, but for some reason git decided there should be an empty file.

This is where the content lives now: https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html

Hopefully, the other PR will fix this. I'll keep this PR open and let the automation close it when #7843 is merged

**Comment by atwixfirster** [comment] 2020-09-10 20:42
Hi, @keharper 

> This is where the content lives now: https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html

I do not agree with you. [Authorization tokens](https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html) page does not provide an info how to use a generated token with `Bearer` , etc.

Thank you

**Comment by BarnyShergold** [comment] 2020-09-10 22:57
@atwixfirster @keharper 
Authorization Tokens page IS now the correct page. What may now be the issue is the content. So it looks like @keharper updated it when it moved. Strictly speaking my PR DOES solve this issues as what you have reported is a missing file/link

However, rather than opening another issue and another PR - if the two of you can agree what changes and additional content need to be added, I can update the new page whilst the PR is open.

I can't just restore the image "graphql-authorization.png" as it no longer exists on the repo.

NOTE : The PR has been approved, so if you can get me the changes before it moves on then I will add them. Otherwise we will have to create a second PR

**Comment by atwixfirster** [comment] 2020-09-10 23:02
Hi, @BarnyShergold 

> I can't just restore the image "graphql-authorization.png" as it no longer exists on the repo.

You can find an image [here](https://raw.githubusercontent.com/magento/devdocs/06b72cd6dbfe9c12df1db8def89f6d787f8885be/src/guides/v2.3/graphql/images/graphql-authorization.png).

Thank you!

**Comment by BarnyShergold** [comment] 2020-09-11 08:03
@atwixfirster - I've added this now (had to update image links and the revoke link) on 2.3 & 2.4 versions. Does this read okay now?

**Closed** 2020-09-11 17:44 UTC
Labels: Progress: PR created
