### ISSUE TITLE
Page Cache

### ISSUE THREAD

**Issue by mttjohnson** [magento/devdocs#366] opened 2015-10-06 21:01 UTC
I'm not seeing much documentation regarding page caching and block caching in the documentation. There is also the topic of private data, and how private data is utilized surrounding caching.

There was a [blog article by Alan Kent last December](http://alankent.me/2014/12/09/magento-2-caching-overview/) that provides some concepts and overview of what was in development at the time, but I'm looking for what the pieces are now, and how to use them.

In a layout block declaration you can define the block as cachable=false, but I've seen instances such as the product detail page where my additional blocks end up getting cached still even with that block declaration. It also looks like any page that has [layout block elements with cachable=false will not utilize private block replacement](https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L103).

I have a block on a product detail page that is rendered depending on if a custom product attribute exists, and the content in the block is different per visitor depending on the value of a cookie. The cookie value can change based on the visitor's preference, so the content in the block could change at any point, but is specific to the visitor.

**Comment by xcomSteveJohnson** [comment] 2015-10-07 15:53
Thanks for pointing this out. Unfortunately, we're booked for GA so I cannot promise this will get done but we'll keep the issue open and update you periodically.

**Comment by xcomSteveJohnson** [comment] 2016-01-11 23:47
Created internal issue MAGEDOC-2500 to track.

**Comment by xcomSteveJohnson** [comment] 2016-07-11 21:29
FWIW, this is underway but could still take a while to complete.

**Comment by xcomSteveJohnson** [comment] 2016-07-29 23:30
@mttjohnson We have a good start on page caching: http://bit.ly/2aBf6t5. Let us know what you think and close this issue if you're happy with it.

**Comment by xcomSteveJohnson** [comment] 2016-10-26 16:11
This is basically a duplicate of #776 so closing. Reopen if you have additional questions.

**Closed by xcomSteveJohnson** 2016-10-26 16:11 UTC
Labels: Enhancement, Waiting for response
