### ISSUE TITLE
Instantiation and resources section unclear on jQuery widget coding standard topic

### ISSUE THREAD

**Issue by DenyVeyten** [magento/devdocs#2427] opened 2018-07-04 12:56 UTC
## This issue is a:
- [ ] Topic clarification request

## Description:
`Instantiation and resources` section unclear (misleading or obsolete?)

## Expected result:
What is `$.mage.components` and `$.mage.extend` methods, example of usage
What is benefits of usage $.mage.extend() and $.mage.components().

**Comment by keharper** [comment] 2018-07-24 15:12
@bdenham  Can you take this on? Be sure to get advice from an architect.

**Comment by dobooth** [comment] 2019-09-16 21:11
Hey @serhiyzhovnir, any interest in updating the page above? You and the team have done so much for widgets lately, it would be great to get this updated as well. No problem at all if you don't want to tackle it!

**Comment by serhiyzhovnir** [comment] 2019-09-17 19:46
Hey @dobooth
Thank you for mentioning me here :)
Can you, please, assign this issue to me?
I would be glad to work on this issue!
Thank you!

**Comment by dobooth** [comment] 2020-01-23 19:46
@serhiyzhovnir Sorry for the delay. Missed the notification. It's all yours!

**Comment by shrielenee** [comment] 2020-04-02 18:58
Whaddup @serhiyzhovnir? You working on this?

**Comment by Santoshziffity** [comment] 2021-02-17 08:50
@magento I am working on this

**Comment by dobooth** [comment] 2021-02-22 17:02
Sweet, @Santoshziffity! Good work picking up the old ones!

**Comment by hguthrie** [comment] 2021-05-12 14:41
@Santoshziffity  Are you still working on this?

**Comment by dshevtsov** [comment] 2024-09-03 19:36
The topic was moved to https://developer.adobe.com/commerce/php/coding-standards/jquery-widgets/.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-php/issues.

**Closed by dshevtsov** 2024-09-03 19:36 UTC
Labels: Help Wanted, 2.3.x, Technical, Progress: ready for dev
