### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/intro/developers_roadmap.html

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [magento/devdocs#6679] opened 2020-02-19 11:09 UTC
# General issue
Link Not Working
## Description:
Link you given on the page not working.

 The Link : validation tool Under Distribute your component.

**Comment by jcalcaben** [comment] 2020-02-20 19:17
Closing as duplicate of #6684

**Closed by jcalcaben** 2020-02-20 19:17 UTC
