### ISSUE TITLE
Can you provide a function to export this site as a pdf file?

### ISSUE THREAD

**Issue by andylhqiu** [magento/devdocs#661] opened 2016-05-16 02:15 UTC
or do you have another way to do this?

**Comment by xcomSteveJohnson** [comment] 2016-05-16 13:10
We currently have no way to do this. You can PDF one page at a time only.

**Comment by xcomSteveJohnson** [comment] 2016-10-26 16:00
Tracking with MAGEDOC-2085.

**Comment by jcalcaben** [comment] 2017-05-11 15:31
Closing issue.

This is a duplicate of: https://github.com/magento/devdocs/issues/330

**Closed by jcalcaben** 2017-05-11 15:31 UTC
Labels: Enhancement
