### ISSUE TITLE
Install permissions instructions are a mess

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#1004] opened 2017-01-20 22:15 UTC
There are a number of issues with the instructions about file permissions. (I believe the technical term for its current status is a "hot mess.") I'm including these in a single issue report, but if it would help to break any/all of these into separate individual issues, let me know, and I'll do so.

Page being addressed:
http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_file-sys-perms.html

Issues:

1. The instructions assume that the user setup you have (one user or two users) is predefined for you. Anybody who is installing on a private server (not shared hosting), however, can set this up however they want. The documentation should provide guidance about what is best practice. In other words, it should recommend a two-user setup, since it's more secure.
2. The instructions for a two-user setup says that "we recommend you create a shared group" for both users, which makes sense, but it is not clear that the entire rest of the directions *assume* that you followed this advice before proceeding. Furthermore, the instructions, which are detailed to the point of being pedantic later, include no direction at all on recursively setting the filesystem to use this shared group. The directions should either be high-level or detailed, but it needs to be consistent, or it's confusing. (For what it's worth, I would argue that it's actually better to be somewhat high level, at least in the section for configuring two users, since this is more complex and unlikely/unwise to be undertaken by a non-technical DIY merchant.)
3. *See #1008.*
4. *See #1009.*

**Comment by hostep** [comment] 2017-01-21 10:31
Not sure if this is relevant, if not, please ignore.

But a couple of months ago, I tried to come up with a theoretical idea of using 3 different users instead of 2, which should result in an even more secure installation.

I still haven't had the chance to actually test this out, to see if my idea would work in practice or not,  and unfortunately probably won't have time in the near future to look into it.

But anyways, here it is: https://github.com/davidalger/capistrano-magento2/issues/32#issuecomment-251208846

**Comment by xcomSteveJohnson** [comment] 2017-01-21 15:25
@scottsb For now, I'd suggest putting points 3 and 4 in separate issues (one issue each). Thanks!

**Comment by xcomSteveJohnson** [comment] 2017-01-23 18:40
@scottsb Added some clarifications for points 1 and 2. Comments:

**Point 1**. Some of Magento's customers choose to go live on shared hosting. We can't tell them not to do that and we can't tell them to do the impossible (set up additional users). I added a paragraph saying that a private server is more secure.

**Point 2**. Not sure what the issue is. 

*  This topic is about file system permissions in production, which means you've already installed Magento, which means you've already set up the shared group. There was already a cross-reference to the topic; I added a sentence saying we assume you've already done that.
*  There are indeed instructions for recursively setting the filesystem to use this shared group, they are these:

```
cd /var/www/html/magento2 && find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \; && chown -R :apache . && chmod u+x bin/magento
```
Please split your points 3 and 4 each into a separate issue and I'll address them at a later time. Thanks!

**Comment by scottsb** [comment] 2017-01-23 19:19
Hi Steve, some followups:

**Point 1**
I think I wasn't clear enough here. To clarify, I'm not saying you should tell people to use a private server. While that is more secure, I understand that you have to document how it can work on shared hosting. My point is that the documentation assumes that you have no control over the user setup (one user or two users), even if you *are* on a private server. That's not true, though. On a private server, you have to make that decision, particularly when running with `php-fpm` instead of `mod_php` (the current best practice). I'm saying that the documentation should explicitly recommend setting up the server with separate users, when possible, rather than taking it as a given. For example, rather than this:

> * One user: Typically, shared hosting providers enable you to log in to the server as one user. This user can log in, transfer files using FTP, and this user also runs the web server.
> * Two users: You must have two users if you cannot log in to the server as, or switch to, the web server user. This type of setup is typical in private hosting or if you have your own Magento server.

Should be something more like (just example wording&mdash;could use some editing):

> * One user: This setup is typically necessary on shared hosting providers, which allow you to access only one user on the server. This single user can log in, transfer files using FTP, and is also the user the web server software runs as.
> * Two users: If you run your own Magento server, it is best to set it up to have separate users: one that you will log in as to transfer files and run command-line utilities, and a separate one that the web server software will run as. When possible, this is preferable, as it is more secure.

**Point 2**
My concern here is mostly resolved by your edit. While this is part of a series of steps, there's enough cross-linking in the documentation that you can't assume users are following a linear process. That's precisely what happened to me. I think the new link and sentence work well.

As far as setting the file system to use the shared group, the command you cited above only changes the permissions (`chmod`). It doesn't change the group (`chgrp` or `chown`). It's a moot point with the new link, though, as this is taken care of in the linked page's instructions:
http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html#perms-set-two-users

**Points 3 & 4**
I'll split these off as requested.

**Comment by xcomSteveJohnson** [comment] 2017-01-23 21:39
@scottsb Thanks for clarifying. I made the changes you suggest; please take a look and close this if you're satisfied. FWIW, even though you can see it only in the `guides/v2.2` branch (Markdown, not HTML), I also updated the topic for 2.2 because directories like `var/di` and `var/generated` have changed names and locations.

**Comment by scottsb** [comment] 2017-01-23 22:00
Looks good, except for one minor typo in both copies: "one that to transfer files" should be "one to transfer files."

(Strictly speaking, the transferring is not the significant point: the point is ownership, which could theoretically be other than the transferring user. But that's a nitpick that's probably not worth pursuing.)

**Closed** 2017-01-23 22:01 UTC
Labels: In progress

**Comment by xcomSteveJohnson** [comment] 2017-01-24 12:21
My motto is “no typo too small”. Fixed. Thanks!
