### ISSUE TITLE
This release is not compatible with PHP 8.1.2

### ISSUE THREAD

**Issue by bvowell1975** [magento/devdocs#9409] opened 2022-04-13 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html

### What's wrong with the content?

output of "magento set:up"
PHP Fatal error:  During inheritance of Countable: Uncaught Exception: Deprecated Functionality: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php on line 206 in /var/mage-src/2.4.4/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(27): Magento\Framework\App\ErrorHandler->handler()
#1 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/WritableArrayRepository.php(22): Composer\Autoload\ClassLoader->loadClass()
#4 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(571): include('...')
#5 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/FilesystemRepository.php(25): Composer\Autoload\ClassLoader->loadClass()
#7 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(571): include('...')
#8 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#9 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/InstalledFilesystemRepository.php(20): Composer\Autoload\ClassLoader->loadClass()
#10 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(571): include('...')
#11 /var/mage-src/2.4.4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#12 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Factory.php(429): Composer\Autoload\ClassLoader->loadClass()
#13 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Factory.php(339): Composer\Factory->addLocalRepository()
#14 /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Factory.php(576): Composer\Factory->createComposer()
#15 /var/mage-src/2.4.4/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create()
#16 /var/mage-src/2.4.4/vendor/magento/framework/Composer/ComposerInformation.php(368): Magento\Framework\Composer\ComposerFactory->create()
#17 /var/mage-src/2.4.4/vendor/magento/framework/Composer/ComposerInformation.php(381): Magento\Framework\Composer\ComposerInformation->getComposer()
#18 /var/mage-src/2.4.4/vendor/magento/framework/Composer/ComposerInformation.php(244): Magento\Framework\Composer\ComposerInformation->getLocker()
#19 /var/mage-src/2.4.4/vendor/magento/framework/App/ProductMetadata.php(120): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#20 /var/mage-src/2.4.4/vendor/magento/framework/App/ProductMetadata.php(80): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#21 /var/mage-src/2.4.4/vendor/magento/framework/Console/Cli.php(98): Magento\Framework\App\ProductMetadata->getVersion()
#22 /var/mage-src/2.4.4/bin/magento(22): Magento\Framework\Console\Cli->__construct()
#23 {main} in /var/mage-src/2.4.4/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php on line 27

### What changes do you propose?

fix attribute

### Anything else that can help to cover this?

no

**Comment by hostep** [comment] 2022-04-14 12:36
@bvowell1975, try upgrading `composer/composer` to the latest version, credits to @BarnyShergold:

<img width="395" alt="Screen Shot 2022-04-14 at 14 35 22" src="https://user-images.githubusercontent.com/85479/163391681-3013ef21-e74e-42e8-b5ec-ae5454048e6a.png">

**Comment by hguthrie** [comment] 2022-04-14 14:09
@bvowell1975 Does this solve your issue?

**Comment by bvowell1975** [comment] 2022-04-14 21:05
No, same result.  I am using Debian Sid, and the newest composer available from that Debian repo is v2.2.9.  I manually downloaded composer v2.3.5 from the getcomposer.org website and tried everything again with PHP 8.1.2, and the exact same errors come up.  I'm reverting back to PHP 7.4.26 right now and 'magento set:up' appears to be functional.

**Comment by bvowell1975** [comment] 2022-04-14 22:28
I'm not sure if this is relevant or not, but PHP 8.1.2 was also throwing MySQL errors about a file not existing.  I'm running and connecting to MySQL through a local unix socket, and TCP/IP connections are disabled completely in the MySQL config.  Is there something different about how PHP 8.1 handles PDO connections and how Magento uses them when connecting over a socket?  My env.php has a blank 'host' entry in the config, and with the 'unix_socket' parameter defined.

**Comment by hostep** [comment] 2022-04-15 09:03
There is more info in this thread: https://github.com/magento/magento2/issues/35306, hopefully you can find an answer there...

**Comment by C4rter** [comment] 2022-04-15 09:23
The issue is the composer module in the vendor folder.
I don't know when but when following the steps in the linked thread, it will update at some point.

If not following the steps there is a point when it won't update anymore and you are stuck with the old module that's incompatible to PHP 8.1

**Comment by bvowell1975** [comment] 2022-04-15 20:44
Can you share the old and new module versions?  I've restored my 2.4.3-p1 backup several times and followed the steps in the other thread, and keep ending up with a 2.4.4 installation that works with PHP 7 but not with PHP 8.  I had a couple of dependency problems in the composer.json that took a bit to sort out, but all the Magento components downloaded and upgraded without complaining.

At the end of my upgrade attempts, I'm left with composer/composer 2.2.12 and the following DB errors when trying "magento set:up":

Cache types config flushed successfully

SQLSTATE[HY000] [2002] No such file or directory

In Abstract.php line 144:

  SQLSTATE[HY000] [2002] No such file or directory

In Abstract.php line 128:

  SQLSTATE[HY000] [2002] No such file or directory

Immediately switching back to PHP 7 gives a functional system with none of those errors, which is why I was thinking this might be some sort of PDO driver problem between PHP7 and PHP8, or something strange with the env.php syntax that isn't picking up all the necessary details for the PDO driver.  As I noted before, I'm running MySQL on a unix socket, and not over TCP/IP.

**Comment by dobooth** [comment] 2022-04-21 18:30
Closing as this is not a docs issue.

**Closed by dobooth** 2022-04-21 18:30 UTC
Labels: Waiting for Response, Progress: ready for grooming

**Comment by bvowell1975** [comment] 2022-04-22 10:20
The docs will need to be updated once the root of this problem is found.  There's obviously something missing or different that should be documented so that someone can upgrade from 2.4.3-p1 to 2.4.4.

**Comment by hostep** [comment] 2022-04-22 10:36
@bvowell1975: make sure that the composer version you are using is at least version 2.1.4 (either a seperate phar you're using, or the `composer/composer` dependency that is installed with Magento if you're using `vendor/bin/composer`), I have the feeling that this might be the problem, because in [version 2.1.3](https://github.com/composer/composer/blob/2.1.3/src/Composer/Repository/ArrayRepository.php#L281-L293) or lower, the `count`  function didn't have the `ReturnTypeWillChange` annotation yet, this was added in [version 2.1.4](https://github.com/composer/composer/blob/2.1.4/src/Composer/Repository/ArrayRepository.php#L281-L294) and fixed a [similarly reported issue](https://github.com/composer/composer/issues/10008).

**Comment by bvowell1975** [comment] 2022-04-22 20:27
I checked that first thing.  I'm on composer v2.2.11.

**Comment by hostep** [comment] 2022-04-25 06:12
Yes but also check the version of the `composer/composer` dependency in your project, it might also have an influence here...

**Comment by hguthrie** [comment] 2022-04-25 16:19
Make sure you are following this guidance for using composer 2: https://devdocs.magento.com/cloud/project/magento-app-properties.html#installing-and-using-composer-2
The latest version used in Cloud template for Commerce 2.4.4  is composer 2.2.4:

```
dependencies:
    php:
        composer/composer: '2.2.4'
```
