### ISSUE TITLE
UI Element code block is not rendering correctly

### ISSUE THREAD

**Issue by BenSpace48** [magento/devdocs#6356] opened 2020-01-08 09:56 UTC
# Bug report

## Description

The observable example in https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_uielement_concept.html is not rendering as a code block, it is using correct Markdown so I'm not sure what the problem is (possibly the whitespace before the backticks?)

![About_the_uiElement_class___Magento_2_Developer_Documentation](https://user-images.githubusercontent.com/8895777/71968421-cd0e2f80-31fc-11ea-9b07-687e6e0f05fb.jpg)

### Steps to reproduce

1. Navigate to https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_uielement_concept.html
1. Scroll down to the code example underneath `The main difference between observe() and track() `

## Expected result

Code is rendered as code not a paragraph.

**Comment by jeff-matthews** [comment] 2020-01-08 13:26
Thanks for reporting @BenSpace48.

The problem is that there is no closing set of back ticks (code fence) _after_ the code example. Adding three back ticks after the code sample will fix this issue.

**Comment by atwixfirster** [comment] 2020-01-09 21:56
Pull request: https://github.com/magento/devdocs/pull/6370

Thanks

**Closed** 2020-01-10 00:02 UTC
Labels: Help wanted, Progress: PR created, good first issue, groomed

**Comment by BenSpace48** [comment] 2020-01-10 12:15
> Thanks for reporting @BenSpace48.
> 
> The problem is that there is no closing set of back ticks (code fence) _after_ the code example. Adding three back ticks after the code sample will fix this issue.

Ah right, I did try adding the closing back ticks but the preview showed lots of other changes so I didn't want to risk breaking the below content.

**Comment by atwixfirster** [comment] 2020-01-10 13:26
Hi, @BenSpace48 !

I did not notice any problems with fix:

<img width="1115" alt="preview" src="https://user-images.githubusercontent.com/13585327/72156159-7f8cf080-33bd-11ea-85cf-ede50fad4453.png">

**Comment by BenSpace48** [comment] 2020-01-14 17:23
Sweet, thanks for fixing @atwixfirster
