### ISSUE TITLE
Update Admin Grids example to include an example for multistore installations

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#8340] opened 2020-12-05 09:33 UTC
# Topic clarification/correction request

The example is not working for multistore installations throwing an error 

```
Item (Magento\Framework\View\Element\UiComponent\DataProvider\Document\Interceptor) with the same ID "1357" already exists.

Exception in /var/www/vhosts/etennism2.yourstaging.eu/httpdocs/vendor/magento/framework/Data/Collection.php:408
```

## Topic Link

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/admin-grid.html

## Description

It needs to be clarified that this example works for single store installations. If you create a multistore installation you will receive an error because the plugin is not taking the `store_id` into account 

The problem is located in the code of the plugin 

```

namespace Dev\Grid\Plugin;

use Dev\Grid\Ui\DataProvider\Category\ListingDataProvider as CategoryDataProvider;
use Magento\Eav\Api\AttributeRepositoryInterface;
use Magento\Framework\App\ProductMetadataInterface;
use Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult;

class AddAttributesToUiDataProvider
{
    /** @var AttributeRepositoryInterface */
    private $attributeRepository;

    /** @var ProductMetadataInterface */
    private $productMetadata;

    /**
     * Constructor
     *
     * @param \Magento\Eav\Api\AttributeRepositoryInterface $attributeRepository
     * @param \Magento\Framework\App\ProductMetadataInterface $productMetadata
     */
    public function __construct(
        AttributeRepositoryInterface $attributeRepository,
        ProductMetadataInterface $productMetadata
    ) {
        $this->attributeRepository = $attributeRepository;
        $this->productMetadata = $productMetadata;
    }

    /**
     * Get Search Result after plugin
     *
     * @param \Dev\Grid\Ui\DataProvider\Category\ListingDataProvider $subject
     * @param \Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult $result
     * @return \Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult
     */
    public function afterGetSearchResult(CategoryDataProvider $subject, SearchResult $result)
    {
        if ($result->isLoaded()) {
            return $result;
        }

        $edition = $this->productMetadata->getEdition();

        $column = 'entity_id';

        if ($edition == 'Enterprise') {
            $column = 'row_id';
        }

        $attribute = $this->attributeRepository->get('catalog_category', 'name');

        $result->getSelect()->joinLeft(
            ['devgridname' => $attribute->getBackendTable()],
            'devgridname.' . $column . ' = main_table.' . $column . ' AND devgridname.attribute_id = '
            . $attribute->getAttributeId(),
            ['name' => 'devgridname.value']
        );

        $result->getSelect()->where('devgridname.value LIKE "B%"');

        return $result;
    }
}

```
The join that is happening will produce multiple repetitions of the same entity_id in multistore thus throwing the error mentioned earlier. 

## Possible solutions

There should be a clarification that this works for single store installations and that the code works for single stores. 
There should be special notice that if you want to work with multistores the plugin must be edited  to fix the join. 

Hopefully there would be an example on how to retrieve the collection's store_id from the grid and how to join it.

**Comment by BarnyShergold** [comment] 2020-12-07 15:09
@hguthrie - I think this is more of a found bug with the plugin rather than a documentation issue. Can we get a developer to take a look at the plugin code on this page and suggest a correction?

**Comment by hguthrie** [comment] 2020-12-08 17:17
@BarnyShergold Thanks, I will search for one.

**Comment by hguthrie** [comment] 2020-12-17 15:00
Update: still looking around for someone to check it out.

**Comment by bdenham** [comment] 2021-02-03 19:48
@hguthrie Any updates for this?

**Comment by hguthrie** [comment] 2021-02-03 20:01
No one has offered any feedback. 😞

**Comment by gixid192** [comment] 2021-04-02 07:49
Hi guys,

I cannot reproduce the error. Could you guys help by listing out the steps?

Here is how I do it:
1. Generate a [medium profile](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-perf-data.html), which according to the docs, will have 3 websites
2. Copy/paste from the tutorial
3. Check the result

I also checked the SQL generated from the plugin, please advise where I could reproduce the issue. Thanks!
```
SELECT `main_table`.*, `devgridname`.`value` AS `name` FROM `catalog_category_entity` AS `main_table` LEFT JOIN `catalog_category_entity_varchar` AS `devgridname` ON devgridname.entity_id = main_table.entity_id AND devgridname.attribute_id = 45 WHERE (devgridname.value LIKE "B%")
```

**Comment by hguthrie** [comment] 2021-04-05 12:50
@ioweb-gr  Can you review the steps to produce the error, compare with @gixid192 steps, and provide feedback? Thanks!

**Comment by ioweb-gr** [comment] 2021-04-06 05:40
It's been about 5 months since I raised the issue. I don't think I have the source code to replicate this any longer.

**Comment by hguthrie** [comment] 2021-04-27 21:09
Closing this issue because we are not able to ascertain whether there is a clear and generic solution for the doc update. If this issue persists and you can share more details, you are welcome to reopen or create a PR with an example.

**Closed by hguthrie** 2021-04-27 21:09 UTC
Labels: Progress: ready for grooming, Waiting for Response
