### ISSUE TITLE
Validation tool for packaged component

### ISSUE THREAD

**Issue by sethsnel** [magento/devdocs#6693] opened 2020-02-20 16:17 UTC
## Topic Link

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/package/package_module.html

## Description

The link to the validation throws an 404. And I would like to validate a Magento 2 component. Where is the validation tool hosted?

## Possible solutions

Rectify link.

**Comment by jcalcaben** [comment] 2020-02-20 19:10
Closing as a duplicate of #6684

**Closed by jcalcaben** 2020-02-20 19:10 UTC
