### ISSUE TITLE
How to create admin grid

### ISSUE THREAD

**Issue by kunal1234gh** [magento/devdocs#1464] opened 2017-10-18 08:52 UTC
Feedback on page: /videos/fundamentals/add-a-new-table-to-database/

Hi 

Can u create a documentation how to create admin grid

**Comment by jeff-matthews** [comment] 2018-02-23 20:05
@kunal1234gh, I'm adding this to a list of suggested topics for community contributions. Stay tunend for updates. Also, I'm closing this as a duplicate of #1465.

**Closed by jeff-matthews** 2018-02-23 20:05 UTC
