### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by C0d3-R3d** [magento/devdocs#9234] opened 2021-11-03 16:38 UTC
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com//guides//v2.3//install-gde//prereq//connect-auth.html

## Description

I am trying to get the Authentication for magento2, so i can download it onto debian buster.
After a lot of trying and research, I found the mention link over internet, but it showing it ain't available.

Command i ran:-

php composer.phar create-project --repository-url=https://repo.magento.com/ magento2 -vv ./magento2 --prefer-dist --no-interaction --dev

## Possible solutions

Share the correct documentation, as i followed the official documentation, as the current documentation on Apache2. 
I tried that too, and got multiple errors so, raising the issue. I will try to replicate it and share so we can work on it. 

## Additional information

Meanwhile adding the total output of raised issue >>>

php composer.phar create-project --repository-url=https://repo.magento.com/ magento2 -vv ./magento2 --prefer-dist --no-interaction --dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details                                                                        
You are using the deprecated option "dev". Dev packages are installed by default now.                                                                       
Creating a "magento2" project at "./magento2"
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html                                                
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html                                                
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html                                                

                                                                             
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  
                                                                             

Exception trace:
 () at phar:///root/magento2/composer.phar/src/Composer/Util/AuthHelper.php:179                                                                             
 Composer\Util\AuthHelper->promptAuthIfNeeded() at phar:///root/magento2/composer.phar/src/Composer/Util/RemoteFilesystem.php:647                           
 Composer\Util\RemoteFilesystem->promptAuthAndRetry() at phar:///root/magento2/composer.phar/src/Composer/Util/RemoteFilesystem.php:314                     
 Composer\Util\RemoteFilesystem->get() at phar:///root/magento2/composer.phar/src/Composer/Util/RemoteFilesystem.php:128                                    
 Composer\Util\RemoteFilesystem->getContents() at phar:///root/magento2/composer.phar/src/Composer/Util/HttpDownloader.php:257                              
 Composer\Util\HttpDownloader->Composer\Util\{closure}() at n/a:n/a
 call_user_func() at phar:///root/magento2/composer.phar/vendor/react/promise/src/React/Promise/Promise.php:49                                              
 React\Promise\Promise->call() at phar:///root/magento2/composer.phar/vendor/react/promise/src/React/Promise/Promise.php:21                                 
 React\Promise\Promise->__construct() at phar:///root/magento2/composer.phar/src/Composer/Util/HttpDownloader.php:283                                       
 Composer\Util\HttpDownloader->addJob() at phar:///root/magento2/composer.phar/src/Composer/Util/HttpDownloader.php:107                                     
 Composer\Util\HttpDownloader->get() at phar:///root/magento2/composer.phar/src/Composer/Repository/ComposerRepository.php:1217                             
 Composer\Repository\ComposerRepository->fetchFile() at phar:///root/magento2/composer.phar/src/Composer/Repository/ComposerRepository.php:932              
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///root/magento2/composer.phar/src/Composer/Repository/ComposerRepository.php:584     
 Composer\Repository\ComposerRepository->hasProviders() at phar:///root/magento2/composer.phar/src/Composer/Repository/ComposerRepository.php:397           
 Composer\Repository\ComposerRepository->loadPackages() at phar:///root/magento2/composer.phar/src/Composer/Repository/RepositorySet.php:183                
 Composer\Repository\RepositorySet->findPackages() at phar:///root/magento2/composer.phar/src/Composer/Package/Version/VersionSelector.php:76               
 Composer\Package\Version\VersionSelector->findBestCandidate() at phar:///root/magento2/composer.phar/src/Composer/Command/CreateProjectCommand.php:428     
 Composer\Command\CreateProjectCommand->installRootPackage() at phar:///root/magento2/composer.phar/src/Composer/Command/CreateProjectCommand.php:202       
 Composer\Command\CreateProjectCommand->installProject() at phar:///root/magento2/composer.phar/src/Composer/Command/CreateProjectCommand.php:164           
 Composer\Command\CreateProjectCommand->execute() at phar:///root/magento2/composer.phar/vendor/symfony/console/Command/Command.php:245                     
 Symfony\Component\Console\Command\Command->run() at phar:///root/magento2/composer.phar/vendor/symfony/console/Application.php:835                         
 Symfony\Component\Console\Application->doRunCommand() at phar:///root/magento2/composer.phar/vendor/symfony/console/Application.php:185                    
 Symfony\Component\Console\Application->doRun() at phar:///root/magento2/composer.phar/src/Composer/Console/Application.php:327                             
 Composer\Console\Application->doRun() at phar:///root/magento2/composer.phar/vendor/symfony/console/Application.php:117                                    
 Symfony\Component\Console\Application->run() at phar:///root/magento2/composer.phar/src/Composer/Console/Application.php:128                               
 Composer\Console\Application->run() at phar:///root/magento2/composer.phar/bin/composer:73                                                                 
 require() at /root/magento2/composer.phar:29

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]                       

Thanks for correcting me in advance.
@magento I am working on this

**Comment by C0d3-R3d** [comment] 2021-11-03 16:42
@magento I am working on this

**Comment by BarnyShergold** [comment] 2021-11-17 16:07
@C0d3-R3d - Not sure what the issue is here.
You said "After a lot of trying and research, I found the mention link over internet, but it showing it ain't available."
The page listed does exist you just have double slashes. It should be `https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html`

I've just followed the instructions and downloaded the repo for Magento CE 2.4.3-p1 with data.

EG to get this : curl -O https://MAG00???????:??????????????????@www.magentocommerce.com/products/downloads/file/Magento-CE-2.4.3-p1_sample_data.tar.gz

You don't need to run `php composer.phar create-project`

As the page exists and the instructions work and the issue seems to be a malformed URL, I am closing this issue.

If you feel there is still a problem with the documentation, please re-open and clarify the issue.

Thanks!

**Closed by BarnyShergold** 2021-11-17 16:07 UTC
Labels: Progress: dev in progress
