### ISSUE TITLE
Imported CSS line very long restricting contributions

### ISSUE THREAD

**Issue by bobbyshaw** [magento/devdocs#205] opened 2015-02-28 16:56 UTC
I was looking to make a contribution to resolve some issues with the site responsiveness but the majority of the css (160,000 characters) is on one line:

https://github.com/magento/devdocs/blob/develop/css/app.css#L275

I presume this is a side-effect of some import process from another site/repository. 

Would you be able to import it so that it maintains formatting? I tried converters myself but I couldn't be sure that it wasn't introducing bugs.

Alternatively, can you can confirm that this is a long-term restriction and will be continually re-imported and therefore any contributions need to re-define selectors and overwrite any statements included here.  

Thanks

**Comment by xcomSteveJohnson** [comment] 2015-03-02 21:42
My undestanding is that app.css is a subset of the magento.com CSS. Because magento.com is responsive, my impression is that the issue is not in the CSS but probably in the implementation of the horizontal nav.

I'll double-check the above and respond as soon as I can.

**Comment by xcomSteveJohnson** [comment] 2015-03-03 17:39
After internal discussions, closing this issue. The source CSS is managed by an internal team who would have to validate any changes to it. 

We are working on a solution for this and appreciate your patience while we do so. We'll keep you posted. Thanks for the offer of help!

**Closed by xcomSteveJohnson** 2015-03-03 17:39 UTC

**Comment by bobbyshaw** [comment] 2015-03-03 17:58
OK, any recommendations on how I can help with the responsive issues or shall I forget it for now?

**Comment by xcomSteveJohnson** [comment] 2015-03-03 18:54
Unfortunately, there's no effective way for you to help. We apologize for the delays but we're currently discussing solutions and will let everyone know when we have one.
